import type { Person } from './types.ts'

export const people: Person[] = [
  {
    slug: 'amara-singh',
    name: 'Amara Singh',
    role: 'Associate Professor and Institute Co-Director',
    group: 'Faculty',
    affiliation: 'Northern Centre for AI',
    bio: 'Leads research on open-ended agents, scientific discovery systems, and evaluation for adaptive AI.',
    image: 'amara',
    researchAreas: ['Open-Ended Learning', 'Evaluation', 'AI Safety'],
    links: {
      website: 'https://example.ac.uk/amara-singh',
      googleScholar: 'https://scholar.google.com',
      email: 'mailto:amara.singh@example.ac.uk',
    },
    featured: true,
  },
  {
    slug: 'marcus-adeyemi',
    name: 'Marcus Adeyemi',
    role: 'Research Scientist',
    group: 'Researchers',
    affiliation: 'London AI Systems Lab',
    bio: 'Studies robotics evaluation, embodied world models, and reproducible benchmarks for physical agents.',
    image: 'marcus',
    researchAreas: ['Robotics', 'World Models', 'Benchmarking'],
    links: {
      website: 'https://example.ac.uk/marcus-adeyemi',
      github: 'https://github.com',
    },
    featured: true,
  },
  {
    slug: 'jules-chen',
    name: 'Jules Chen',
    role: 'PhD Student',
    group: 'PhD Students',
    affiliation: 'Eastern Machine Intelligence Lab',
    bio: 'Builds interactive environments for studying how language agents discover new tool-use strategies.',
    image: 'jules',
    researchAreas: ['Language Models', 'Agents', 'Tool Use'],
    links: {
      website: 'https://example.ac.uk/jules-chen',
      github: 'https://github.com',
    },
  },
  {
    slug: 'eve-morrison',
    name: 'Eve Morrison',
    role: 'PhD Student',
    group: 'PhD Students',
    affiliation: 'Northern Centre for AI',
    bio: 'Develops safety cases and reporting formats for self-improving and continually learning systems.',
    image: 'eve',
    researchAreas: ['AI Safety', 'Evaluation', 'Governance'],
    links: {
      googleScholar: 'https://scholar.google.com',
      email: 'mailto:eve.morrison@example.ac.uk',
    },
  },
  {
    slug: 'samira-patel',
    name: 'Samira Patel',
    role: 'Research Engineer',
    group: 'Research Engineers',
    affiliation: 'London AI Systems Lab',
    bio: 'Designs distributed training, experiment tracking, and infrastructure for large-scale research programmes.',
    researchAreas: ['ML Systems', 'Infrastructure', 'Distributed Training'],
    links: {
      github: 'https://github.com',
      linkedin: 'https://www.linkedin.com',
    },
    featured: true,
  },
  {
    slug: 'thomas-okoro',
    name: 'Thomas Okoro',
    role: 'Software Engineer',
    group: 'Software Engineers',
    affiliation: 'BOLD Institute',
    bio: 'Builds web platforms and data tooling that make research outputs reusable across the institute.',
    researchAreas: ['Research Tooling', 'Data', 'Web Platforms'],
    links: {
      github: 'https://github.com',
      linkedin: 'https://www.linkedin.com',
    },
  },
  {
    slug: 'nina-berg',
    name: 'Nina Berg',
    role: "Master's Student",
    group: "Master's Students",
    affiliation: 'Eastern Machine Intelligence Lab',
    bio: 'Works on representation learning for controllable generative models and evaluation dashboards.',
    researchAreas: ['Representation Learning', 'Generative Models', 'Evaluation'],
    links: {
      website: 'https://example.ac.uk/nina-berg',
    },
  },
  {
    slug: 'leo-williams',
    name: 'Leo Williams',
    role: 'Visiting Student',
    group: 'Visiting Students',
    affiliation: 'BOLD Institute',
    bio: 'Explores multi-agent reinforcement learning settings for coordination and emergent communication.',
    researchAreas: ['Multi-Agent RL', 'Reinforcement Learning', 'Coordination'],
    links: {
      website: 'https://example.ac.uk/leo-williams',
    },
  },
  {
    slug: 'marta-garcia',
    name: 'Marta Garcia',
    role: 'BOLD Fellow',
    group: 'Fellows',
    affiliation: 'BOLD Institute',
    bio: 'Leads a fellowship project on language-model evaluation under distribution shift and long-horizon use.',
    researchAreas: ['Language Models', 'Evaluation', 'AI Safety'],
    links: {
      googleScholar: 'https://scholar.google.com',
      website: 'https://example.ac.uk/marta-garcia',
    },
  },
  {
    slug: 'oliver-hart',
    name: 'Oliver Hart',
    role: 'Programme Manager',
    group: 'Staff',
    affiliation: 'BOLD Institute',
    bio: 'Coordinates institute programmes, partnerships, visitor processes, and research operations.',
    researchAreas: ['Research Operations', 'Partnerships'],
    links: {
      email: 'mailto:oliver.hart@example.ac.uk',
    },
  },
  {
    slug: 'fatima-rahman',
    name: 'Fatima Rahman',
    role: 'Affiliate Researcher',
    group: 'Affiliates',
    affiliation: 'Public Interest AI Network',
    bio: 'Collaborates on governance, public datasets, and evidence standards for high-impact AI systems.',
    researchAreas: ['Governance', 'Public Datasets', 'Evaluation'],
    links: {
      website: 'https://example.ac.uk/fatima-rahman',
    },
  },
  {
    slug: 'alex-kim',
    name: 'Alex Kim',
    role: 'Alumnus',
    group: 'Alumni',
    affiliation: 'BOLD Institute',
    bio: 'Former student researcher on behavioural portfolios for continually learning systems.',
    researchAreas: ['Continual Learning', 'Evaluation'],
    links: {
      website: 'https://example.ac.uk/alex-kim',
    },
    alumni: true,
  },
]

export const roleOrder = [
  'Faculty',
  'Researchers',
  'PhD Students',
  'Research Engineers',
  'Software Engineers',
  "Master's Students",
  'Visiting Students',
  'Fellows',
  'Staff',
  'Affiliates',
  'Alumni',
]
